import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Contact Page",
	description: "contact page generated by next",
};

export default function ContactPage () {
	return (
		<>
			<span>
				Contact Page
			</span>
		</>
	)
} 